volumes:
  esdata01:
    driver: local

services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=elasticsearch-demo
      - discovery.type=single-node
      - ELASTIC_PASSWORD=e46yYv8rTVy3EgbTTs
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.license.self_generated.type=basic
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
